# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:6.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123qwe

    ports:
      - 27017:27017
    volumes:
      - ./backups:/backups
      - ./db:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123qwe
      ME_CONFIG_MONGODB_URL: "mongodb://root:123qwe@mongo:27017/"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123qwe

