import './globals.css'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth/next'
import { SessionProvider, getSession } from 'next-auth/react'
import { Inter } from 'next/font/google'
import { authOptions } from './api/auth/[...nextauth]/route'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Series Planner',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode,
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
          {children}
      </body>
    </html>
  )
}
